[package]
name = "setsid"
version = "0.1.0"
authors = ["Vincent Haupert <mail@vincent-haupert.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
