[package]
name = "setsid-posix"
description = "A POSIX implementation of setsid(1)"
version = "0.1.0"
authors = ["Vincent Haupert <mail@vincent-haupert.de>"]
edition = "2021"

[dependencies]
nix = "^0.26"
clap = { version = "^4.0", features = [ "derive" ] }
