[package]
name = "setsid"
description = "A POSIX implementation of setsid(1)"
version = "0.1.0"
authors = ["Vincent Haupert <mail@vincent-haupert.de>"]
edition = "2018"

[dependencies]
nix = "^0.23"
clap = "^2.33"
