name: macOS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup rust toolchain
        run: |
          rustup show
      - name: Setup for Apple Silicon
        run: |
          sudo xcode-select -s /Applications/Xcode_12.2.app/Contents/Developer/
          echo "SDKROOT=$(xcrun -sdk macosx11.0 --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.0 --show-sdk-platform-version)" >> $GITHUB_ENV
        if: matrix.target == 'aarch64-apple-darwin'
      - name: Ensure we have our goal target installed
        run: |
          rustup target install "${{ matrix.target }}"
      - name: Build
        run: |
          cargo build --release --target="${{ matrix.target }}"
      - uses: actions/upload-artifact@v2
        with:
          name: setsid-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/setsid
          if-no-files-found: error

