name: macOS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup rust toolchain
        run: |
          rustup show
      - name: Set SDKROOT
        run: echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
      - name: Set MACOSX_DEPLOYMENT_TARGET
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV
      - name: Ensure we have our goal target installed
        run: |
          rustup target install "${{ matrix.target }}"
      - name: Build
        run: |
          cargo build --release --target="${{ matrix.target }}"
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: setsid-posix-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/setsid-posix
          if-no-files-found: error

